import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

export default [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  // next-env.d.ts is regenerated by Next on every build and its contents are
  // not ours to fix — it emits a triple-slash reference the TS rules reject.
  { ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts'] },
];
